import { State, Order, Stage, localDate } from './model';
export function seed(): State {
    const day = (n: number) => {
        const d = new Date();
        d.setDate(d.getDate() + n);
        return localDate(d);
    };
    const contacts = [
        {
            name: 'Алексей Воронов',
            role: 'Диспетчер этапа',
            phone: '+70000000001',
        },
        { name: 'Сергей Ким', role: 'Перевозчик', phone: '+70000000002' },
    ];
    const points = [
        'Москва, склад поставщика',
        'Саратов, грузовой терминал',
        'Петропавл, ж/д терминал',
        'Шымкент, грузовой терминал',
        'Шымкент, склад «Юг»',
        'Шымкент, магазин «Дом»',
    ];
    const stages: Stage[] = points.slice(0, -1).map((from, i) => ({
        id: `stage-${i}`,
        from,
        to: points[i + 1],
        transport: [
            'Малый грузовик',
            'Большой грузовик',
            'Грузовой поезд',
            'Малый грузовик',
            'Городская доставка',
        ][i],
        status: i < 2 ? 'done' : i === 2 ? 'current' : 'next',
        date: day(i - 2),
        contacts: [
            ...contacts,
            {
                name: i === 2 ? 'Ирина Белова' : 'Данияр Омаров',
                role: i === 2 ? 'Терминал прибытия' : 'Водитель',
                phone: '+70000000003',
            },
            {
                name: 'Мария Волкова',
                role: 'Склад / приёмка',
                phone: '+70000000004',
            },
        ],
    }));
    const base: Order = {
        id: 'JL-2048',
        companyId: 'c1',
        from: points[0],
        to: points[5],
        pickup: day(-3),
        date: day(3),
        cargo: 'Посуда и товары для дома',
        quantity: 20,
        unit: 'коробок',
        comment: 'Хрупкий груз. Позвонить перед доставкой.',
        status: 'transit',
        stages,
        agreedPrice: 285000,
        updated: new Date().toISOString(),
        files: [],
        issues: [],
    };
    return {
        version: 1,
        profile: {
            name: 'Анна Смирнова',
            company: 'Магазин «Дом»',
            phone: '+70000000000',
            city: 'Шымкент',
            bin: '',
            notifications: true,
        },
        companies: [
            {
                id: 'c1',
                name: 'Qaz Logistics',
                city: 'Шымкент',
                description:
                    'Автомобильные и железнодорожные перевозки. Склады в Казахстане, доставка из России.',
                relation: 'confirmed',
                phone: '+70000000001',
            },
            {
                id: 'c2',
                name: 'Steppe Cargo',
                city: 'Алматы',
                description:
                    'Региональная доставка, сборные грузы и снабжение магазинов.',
                relation: 'confirmed',
                phone: '+70000000005',
            },
            {
                id: 'c3',
                name: 'Nomad Freight',
                city: 'Астана',
                description:
                    'Промышленные грузы, перевозка сырья и регулярные поставки.',
                relation: 'available',
                phone: '+70000000006',
            },
        ],
        orders: [
            base,
            {
                ...base,
                id: 'JL-2049',
                from: 'Алматы, склад поставщика',
                quantity: 8,
                status: 'offer',
                stages: [
                    {
                        ...stages[0],
                        from: 'Алматы, склад поставщика',
                        to: points[5],
                        status: 'next',
                        date: day(4),
                    },
                ],
                agreedPrice: undefined,
                offer: {
                    amount: 64000,
                    eta: day(4),
                    kind: 'initial',
                    reason: 'Забор груза, перевозка и доставка до магазина включены.',
                    status: 'pending',
                },
                pickup: day(1),
                date: day(4),
                companyId: 'c2',
            },
            {
                ...base,
                id: 'JL-2045',
                cargo: 'Торговое оборудование',
                quantity: 3,
                unit: 'паллет',
                originalEta: day(0),
                date: day(2),
                delay: 'Задержка отправления поезда на терминале. Компания согласовала ближайшее отправление.',
                extra: {
                    kind: 'extra',
                    amount: 18000,
                    eta: day(2),
                    reason: 'Дополнительная упаковка оборудования по результатам осмотра.',
                    status: 'pending',
                },
            },
            {
                ...base,
                id: 'JL-2042',
                status: 'delivered',
                date: day(-2),
                pickup: day(-7),
                stages: stages.map((s, i) => ({
                    ...s,
                    date: day(-6 + i),
                    status: 'done',
                })),
                proof: 'Груз передан получателю: 20 коробок, без замечаний. Акт приёмки № 2042.',
                invoice: { number: 'СЧ-2042', amount: 285000, paid: true },
            },
            {
                ...base,
                id: 'JL-2050',
                status: 'waiting',
                companyId: 'c2',
                from: 'Алматы, склад поставщика',
                pickup: day(2),
                date: day(5),
                stages: [],
                agreedPrice: undefined,
                cargo: 'Упаковочные материалы',
                quantity: 10,
            },
            {
                ...base,
                id: 'JL-2047',
                from: 'Шымкент, склад «Юг»',
                cargo: 'Посуда',
                quantity: 4,
                status: 'planned',
                stages: [{ ...stages[4], status: 'next' }],
                batchId: 'b1',
                agreedPrice: 12000,
                invoice: { number: 'СЧ-2047', amount: 12000, paid: false },
            },
        ],
        supplies: [
            {
                id: 's1',
                title: 'Пополнение магазина «Дом»',
                companyId: 'c2',
                from: 'Алматы, склад поставщика',
                to: points[5],
                cargo: 'Товары для дома',
                quantity: 8,
                unit: 'коробок',
                mode: 'weekly',
                weekdays: [1, 4],
                monthDay: 1,
                automatic: false,
                paused: false,
                skipped: [],
                price: 64000,
                approved: true,
            },
            {
                id: 's2',
                title: 'Упаковка по потребности',
                companyId: 'c1',
                from: 'Шымкент, склад «Юг»',
                to: points[5],
                cargo: 'Упаковка',
                quantity: 2,
                unit: 'паллет',
                mode: 'manual',
                weekdays: [1],
                monthDay: 1,
                automatic: true,
                paused: false,
                skipped: [],
                price: 15000,
                approved: true,
            },
        ],
        batches: [
            {
                id: 'b1',
                companyId: 'c1',
                warehouse: 'Шымкент, склад «Юг»',
                cargo: 'Посуда',
                unit: 'коробок',
                onHand: 20,
                baseReserved: 0,
                source: 'Приёмка ПР-108 · поставка из Москвы',
            },
            {
                id: 'b2',
                companyId: 'c2',
                warehouse: 'Алматы, склад «Восток»',
                cargo: 'Торговые стеллажи',
                unit: 'шт.',
                onHand: 12,
                baseReserved: 2,
                source: 'Приёмка ПР-112',
            },
        ],
    };
}
