import type {
    ShipperOrder,
    ShipperProfile,
    ShipperVehicleTypeOption,
} from '../_types/shipper';

export const shipperProfileMock: ShipperProfile = {
    id: 101,
    name: 'Алина Кайратова',
    phone: '+7 (701) 442 - 18 - 09',
    type: 'company',
    companyName: 'LogiTrade KZ',
    bin: '221040012345',
    city: 'Алматы',
};

export const shipperVehicleTypesMock: ShipperVehicleTypeOption[] = [
    {
        type: 'tent',
        label: 'Тент',
        description: 'Для паллетных и универсальных грузов.',
        highlight: 'До 20 т',
    },
    {
        type: 'refrigerator',
        label: 'Рефрижератор',
        description: 'Для температурных и скоропортящихся грузов.',
        highlight: 'Холодовая цепь',
    },
    {
        type: 'van',
        label: 'Фургон',
        description: 'Для защищенной городской и межгородской доставки.',
        highlight: 'Компактная подача',
    },
    {
        type: 'flatbed',
        label: 'Платформа',
        description: 'Для негабарита и погрузки сверху.',
        highlight: 'Открытая база',
    },
    {
        type: 'manipulator',
        label: 'Манипулятор',
        description: 'Когда нужна машина с собственной погрузкой.',
        highlight: 'С краном',
    },
];

export const shipperOrdersMock: ShipperOrder[] = [
    {
        id: 7001,
        orderNumber: 'JS-7001',
        fromCity: 'Алматы',
        toCity: 'Астана',
        pickupAddress: 'Склад A, Северное кольцо 118',
        dropoffAddress: 'Астана, Индустриальный парк 7',
        cargoTitle: 'Бытовая химия',
        cargoWeightTons: 12,
        cargoVolumeM3: 28,
        vehicleType: 'tent',
        status: 'waitingDriver',
        price: 165000,
        createdAt: '11 июня, 10:15',
        pickupDate: '12 июня, 09:00',
        eta: 'После назначения машины',
        assignedDriverName: null,
        assignedVehicleModel: null,
        assignedVehiclePlate: null,
        currentPoint: 'Ожидает назначения водителя',
        comment: 'Позвонить логисту за час до подачи.',
    },
    {
        id: 7002,
        orderNumber: 'JS-7002',
        fromCity: 'Астана',
        toCity: 'Караганда',
        pickupAddress: 'Склад Delta, пр. Кабанбай батыра 53',
        dropoffAddress: 'Караганда, ул. Гоголя 41',
        cargoTitle: 'Медицинское оборудование',
        cargoWeightTons: 4,
        cargoVolumeM3: 16,
        vehicleType: 'van',
        status: 'vehicleAssigned',
        price: 182000,
        createdAt: '10 июня, 16:40',
        pickupDate: '12 июня, 14:30',
        eta: '12 июня, 18:30',
        assignedDriverName: 'Ерлан Тажиев',
        assignedVehicleModel: 'Mercedes Sprinter',
        assignedVehiclePlate: '938 KZA 02',
        currentPoint: 'Машина выехала на погрузку',
        comment: 'Оборудование хрупкое, закрепить ремнями.',
    },
    {
        id: 7003,
        orderNumber: 'JS-7003',
        fromCity: 'Алматы',
        toCity: 'Шымкент',
        pickupAddress: 'Холодный склад Joool, Райымбека 210',
        dropoffAddress: 'Шымкент, РЦ Fresh Hub',
        cargoTitle: 'Охлажденные продукты',
        cargoWeightTons: 14,
        cargoVolumeM3: 34,
        vehicleType: 'refrigerator',
        status: 'inTransit',
        price: 248000,
        createdAt: '10 июня, 08:20',
        pickupDate: '11 июня, 07:30',
        eta: 'Сегодня, 19:40',
        assignedDriverName: 'Аскар Сейдахметов',
        assignedVehicleModel: 'Volvo FH 500',
        assignedVehiclePlate: '777 ABA 02',
        currentPoint: 'Тараз, объездная дорога',
        comment: 'Поддерживать температуру +4°C весь маршрут.',
    },
    {
        id: 7004,
        orderNumber: 'JS-7004',
        fromCity: 'Павлодар',
        toCity: 'Алматы',
        pickupAddress: 'Павлодар, склад МебельЛайн',
        dropoffAddress: 'Алматы, ул. Розыбакиева 275',
        cargoTitle: 'Корпусная мебель',
        cargoWeightTons: 18,
        cargoVolumeM3: 41,
        vehicleType: 'flatbed',
        status: 'delivered',
        price: 315000,
        createdAt: '6 июня, 11:10',
        pickupDate: '7 июня, 08:00',
        eta: 'Доставлено 8 июня, 21:15',
        assignedDriverName: 'Нуртас Бекенов',
        assignedVehicleModel: 'DAF XF 480',
        assignedVehiclePlate: '512 LPA 01',
        currentPoint: 'Доставка завершена',
        comment: 'Разгрузка на задний пандус склада.',
    },
    {
        id: 7005,
        orderNumber: 'JS-7005',
        fromCity: 'Актобе',
        toCity: 'Костанай',
        pickupAddress: 'Актобе, база СтройСнаб',
        dropoffAddress: 'Костанай, ул. Аль-Фараби 88',
        cargoTitle: 'Строительные блоки',
        cargoWeightTons: 16,
        cargoVolumeM3: 22,
        vehicleType: 'manipulator',
        status: 'cancelled',
        price: 289000,
        createdAt: '5 июня, 13:25',
        pickupDate: '9 июня, 10:00',
        eta: 'Заявка отменена',
        assignedDriverName: null,
        assignedVehicleModel: null,
        assignedVehiclePlate: null,
        currentPoint: 'Отменено заказчиком',
        comment: 'Нужна была выгрузка манипулятором на объекте.',
    },
];

export const activeShipperOrderMock: ShipperOrder | null =
    shipperOrdersMock.find((order) => order.status === 'inTransit') ?? null;
