import type { Metadata } from 'next';
import { Inter_Tight } from 'next/font/google';

const interTight = Inter_Tight({ subsets: ['latin', 'cyrillic'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={interTight.className}>{children}</body>
        </html>
    );
}