import type { Metadata } from 'next';
import { Inter_Tight } from 'next/font/google';
import './globals.css';
import Head from 'next/head';
import { SpeedInsights } from '@vercel/speed-insights/next';

const interTight = Inter_Tight({ subsets: ['latin', 'cyrillic'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Head>
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
                />
            </Head>
            <body className={interTight.className}>
                {children}
                <SpeedInsights />
            </body>
        </html>
    );
}
