import type { Metadata, Viewport } from 'next';
import { Inter_Tight, Inter } from 'next/font/google';
import './globals.css';
import { SpeedInsights } from '@vercel/speed-insights/next';
import ReactQueryProvider from '@/lib/react-query';
import { Toaster } from 'react-hot-toast';
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const interTight = Inter_Tight({ subsets: ['latin', 'cyrillic'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export const viewport: Viewport = {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    minimumScale: 1,
    height: 'device-height',
    userScalable: false,
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={cn("font-sans", inter.variable)}>
            <body className={interTight.className}>
                <ReactQueryProvider>
                    <Toaster containerClassName="mt-10" />
                    {children}
                    <SpeedInsights />
                </ReactQueryProvider>
            </body>
        </html>
    );
}
