import type {
    CargoDocument,
    CargoShipperContact,
    CargoTrip,
    Driver,
    TripStep,
    Vehicle,
} from '../_types/cargo';

export const driverMock: Driver = {
    id: 1,
    fullName: 'Аскар Сейдахметов',
    phone: '+7 (777) 701 - 14 - 22',
    status: 'verified',
    fleet: 'Joool Cargo Almaty',
    experienceYears: 8,
    assignedVehicleId: 17,
    licenseNumber: 'KZ 044381927',
    city: 'Алматы',
};

export const vehicleMock: Vehicle = {
    id: 17,
    model: 'Volvo FH 500',
    plateNumber: '777 ABA 02',
    trailerNumber: 'TR 438 AK',
    type: 'refrigerator',
    capacityTons: 20,
    fleet: 'Joool Cargo Almaty',
    year: 2021,
};

export const activeTripMock: CargoTrip = {
    id: 4042,
    routeLabel: 'Алматы - Шымкент',
    fromCity: 'Алматы',
    toCity: 'Шымкент',
    currentStatus: 'inTransit',
    cargoTitle: 'Охлажденные продукты',
    cargoWeightTons: 14,
    cargoVolumeM3: 34,
    pickupPoint: 'Склад Joool Cargo, Северное кольцо',
    pickupAddress: 'Алматы, Северное кольцо, 28/4',
    dropoffPoint: 'РЦ Shymkent Fresh, Каратау',
    dropoffAddress: 'Шымкент, район Каратау, ул. Байдибек би, 126',
    currentPoint: 'Тараз, объездная дорога',
    distanceKm: 182,
    eta: 'Сегодня, 19:40',
    departureDate: '11 июня, 08:30',
    arrivalDate: '11 июня, 19:40',
    referenceNumber: 'JC-4042',
};

export const cargoShipperContactsMock: CargoShipperContact[] = [
    {
        id: 1,
        orderNumber: 'JS-7003',
        companyName: 'LogiTrade KZ',
        contactName: 'Алина Кайратова',
        phone: '+7 (701) 442 - 18 - 09',
        cargoTitle: 'Охлажденные продукты',
        pickupPoint: 'Холодный склад Joool',
        pickupAddress: 'Алматы, Райымбека 210',
        dropoffPoint: 'РЦ Fresh Hub',
        dropoffAddress: 'Шымкент, ул. Байдибек би, 126',
        status: 'loaded',
    },
    {
        id: 2,
        orderNumber: 'JS-7011',
        companyName: 'Green Market',
        contactName: 'Руслан Темиров',
        phone: '+7 (777) 118 - 42 - 66',
        cargoTitle: 'Овощи и зелень',
        pickupPoint: 'Склад Green Market',
        pickupAddress: 'Алматы, ул. Бекмаханова 92',
        dropoffPoint: 'Магазин Green Market',
        dropoffAddress: 'Тараз, пр. Толе би 44',
        status: 'inTransit',
    },
    {
        id: 3,
        orderNumber: 'JS-7018',
        companyName: 'Shymkent Fresh',
        contactName: 'Мадина Омарова',
        phone: '+7 (705) 330 - 27 - 41',
        cargoTitle: 'Молочная продукция',
        pickupPoint: 'Фермерский хаб Alatau',
        pickupAddress: 'Алматы, Кульджинский тракт 18',
        dropoffPoint: 'РЦ Shymkent Fresh',
        dropoffAddress: 'Шымкент, район Каратау, ул. Байдибек би, 126',
        status: 'awaitingDelivery',
    },
];

export const tripStatuses: TripStep[] = [
    {
        id: 1,
        title: 'Рейс назначен',
        description: 'Подтвержден маршрут и документы по заявке',
        status: 'planned',
        state: 'done',
    },
    {
        id: 2,
        title: 'Погрузка LogiTrade KZ',
        description: 'Охлажденные продукты приняты и закреплены в кузове',
        status: 'loading',
        state: 'done',
        orderNumber: 'JS-7003',
        shipperName: 'LogiTrade KZ',
        contactName: 'Алина Кайратова',
        contactPhone: '+7 (701) 442 - 18 - 09',
        address: 'Алматы, Райымбека 210',
        timeLabel: '11 июня, 07:30',
    },
    {
        id: 3,
        title: 'Погрузка Green Market',
        description: 'Овощи и зелень загружены второй партией',
        status: 'loading',
        state: 'done',
        orderNumber: 'JS-7011',
        shipperName: 'Green Market',
        contactName: 'Руслан Темиров',
        contactPhone: '+7 (777) 118 - 42 - 66',
        address: 'Алматы, ул. Бекмаханова 92',
        timeLabel: '11 июня, 08:10',
    },
    {
        id: 4,
        title: 'Погрузка Shymkent Fresh',
        description: 'Молочная продукция загружена с контролем температуры',
        status: 'loading',
        state: 'done',
        orderNumber: 'JS-7018',
        shipperName: 'Shymkent Fresh',
        contactName: 'Мадина Омарова',
        contactPhone: '+7 (705) 330 - 27 - 41',
        address: 'Алматы, Кульджинский тракт 18',
        timeLabel: '11 июня, 08:30',
    },
    {
        id: 5,
        title: 'В пути',
        description: 'Транспорт следует по основному маршруту с тремя заказами',
        status: 'inTransit',
        state: 'current',
    },
    {
        id: 6,
        title: 'Доставка Green Market',
        description: 'Промежуточная разгрузка овощей и зелени',
        status: 'unloading',
        state: 'upcoming',
        orderNumber: 'JS-7011',
        shipperName: 'Green Market',
        contactName: 'Руслан Темиров',
        contactPhone: '+7 (777) 118 - 42 - 66',
        address: 'Тараз, пр. Толе би 44',
        timeLabel: 'Сегодня, 16:20',
    },
    {
        id: 7,
        title: 'Доставка LogiTrade KZ',
        description: 'Передача охлажденных продуктов на склад получателя',
        status: 'unloading',
        state: 'upcoming',
        orderNumber: 'JS-7003',
        shipperName: 'LogiTrade KZ',
        contactName: 'Алина Кайратова',
        contactPhone: '+7 (701) 442 - 18 - 09',
        address: 'Шымкент, ул. Байдибек би, 126',
        timeLabel: 'Сегодня, 19:10',
    },
    {
        id: 8,
        title: 'Доставка Shymkent Fresh',
        description: 'Финальная разгрузка молочной продукции в РЦ',
        status: 'unloading',
        state: 'upcoming',
        orderNumber: 'JS-7018',
        shipperName: 'Shymkent Fresh',
        contactName: 'Мадина Омарова',
        contactPhone: '+7 (705) 330 - 27 - 41',
        address: 'Шымкент, район Каратау, ул. Байдибек би, 126',
        timeLabel: 'Сегодня, 19:40',
    },
    {
        id: 9,
        title: 'Рейс завершен',
        description: 'Все заказы доставлены, закрывающие документы подписаны',
        status: 'completed',
        state: 'upcoming',
    },
];

export const documentsMock: CargoDocument[] = [
    {
        id: 1,
        templateId: 'driver-license',
        title: 'Водительское удостоверение',
        number: '12AB 449212',
        expiresAt: '02.12.2027',
        status: 'valid',
        scope: 'driver',
        ownerLabel: 'Аскар Сейдахметов',
    },
    {
        id: 2,
        templateId: 'medical-certificate',
        title: 'Медицинская справка',
        number: 'MED 004218',
        expiresAt: '28.06.2026',
        status: 'expiring',
        scope: 'driver',
        ownerLabel: 'Аскар Сейдахметов',
    },
    {
        id: 3,
        templateId: 'truck-registration',
        title: 'СТС тягача',
        number: 'STS 882190',
        expiresAt: '13.09.2028',
        status: 'valid',
        scope: 'vehicle',
        ownerLabel: 'Volvo FH 500',
    },
    {
        id: 4,
        templateId: 'insurance-policy',
        title: 'Страховой полис',
        number: 'INS 110482',
        expiresAt: '01.05.2026',
        status: 'expired',
        scope: 'vehicle',
        ownerLabel: 'Volvo FH 500',
    },
];
